### PR TITLE
hu locale update

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by jeromerobert** [comment]
Merged as fd6e73e

**Comment by ovari** [comment]
Thank you for promptly accepting hu locale updates. Can you please advise when [Flathub](https://flathub.org/apps/details/com.github.jeromerobert.pdfarranger) will have the update? Thank you once again.

**Comment by dreua** [comment]
Szia ovari, köszönöm szépen! - Thank you for the translation! (Unfortunately that is where my Hungarian skills come to an end.)

Since I take care of the Flatpaks I'll answer this: The flatpaks on Flathub contain only the released versions. I believe that Jerome will include this change in 1.6.0 which should be released in the near future (days to weeks), see  #216 for more on that. Flathub will be updated as soon as I find the time, usually between hours to a few days after release. Feel free to watch the [flatpak repository](https://github.com/flathub/com.github.jeromerobert.pdfarranger) to get notified of updates and/or ping me if I should ever forget one.

I can also make a test build from current master if that helps you. (Downsides: They seem to be removed after less than 20 days and probably don't update automatically, so for testing only. - See [this pr](https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/5) for example, which is a 404 now.)

While I can't comment on the actual translation, I tested and it looks all translated and good to me, just fixed three underscores showing up.

**Comment by jeromerobert** [comment]
> I believe that Jerome will include this change in 1.6.0 which should be released in the near future (days to weeks)

I'll release 1.6.0 tomorrow.

**Comment by ovari** [comment]
Does `locale hu (Hungarian - magyar) update (#219)` get added to the release notes at https://github.com/jeromerobert/pdfarranger/issues/216#issuecomment-650080492? Thank you

**Pull request closed without merging**
