### PR TITLE
Add img2pdf to Win32.md

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
It works well in MSYS2, but for an unknown reason `img2pdf` is not in the package.

**Comment by jeromerobert** [comment]
If you manage to install img2pdf with `/mingw64/bin/python3 -m pip install --user img2pdf` that should work. I guess you'll have to install https://packages.msys2.org/package/mingw-w64-x86_64-python-pillow

**Comment by mimi89999** [comment]
@jeromerobert That's exactly what I added to `Win32.md` in this PR.

**Comment by jeromerobert** [comment]
Oh sorry I did not see your commit. I'll try it soon.

**Comment by jeromerobert** [comment]
I also cannot find why img2pdf does not get included in the `.msi` and the `.zip` archive. That will require some debugging of cx_Freeze.

**Comment by mimi89999** [comment]
img2pdf goes into the libs zip. Loading it does not work because Pillow imports distutils. Please see the next PR.

**Comment by mimi89999** [comment]
@jeromerobert did you manage to build a working package?

**Comment by jeromerobert** [comment]
@mimi89999 Yes I did. I also updated my Docker image with your changes: https://github.com/jeromerobert/pdfarranger-docker-ci/commit/36958693c6cb540e065b89260c9c62280dad5949. Merci Michel pour ton travail, ce sera certainement apprécié.

**Pull request merged**
