### PR TITLE
Update data files

### PR DESCRIPTION
**Pull request by fabaff**
Would no longer require to carry a patch for the Fedora package.

Thanks

P.S. Sorry, #69 was incomplete.

### CODE REVIEW

**Comment by jeromerobert** [comment]
Icon are installed by DistUtilsExtra so I prefer #69. Merged as 72fd589, closing.

**Comment by fabaff** [comment]
The icons may be installed by DistUtilsExtra but they are not available during the RPM build process. It seems also that DistUtilsExtra is responsible that the l10n stuff can be picked-up by the RPM helper scripts.

**Comment by jeromerobert** [comment]
Yes DistUtilsExtra is also responsible for the I10n. Is it also not working during the RPM process ? Is installation with `pip3 install --user .` also broken (i.e. icon missings) ?

**Comment by fabaff** [comment]
No, a wild guess is that DistUtilsExtra is doing too much already.

**Pull request closed without merging**
