### PR TITLE
Add support for image files

### PR DESCRIPTION
**Pull request by mimi89999**
TODO:
- [x] Identify supported fileformat
- [x] Add setup changes
- [x] The pot file should be regenerated in a separate commit because there are unrelated changes
- [x] Don't keep 2 temp files

@jeromerobert I don't quite understand what you mean by _optional (in [...] and in the setup.py)_.

### CODE REVIEW

**Comment by dreua** [comment]
Hey, great to see someone working on this!

Related issue: https://github.com/jeromerobert/pdfarranger/issues/45#issuecomment-454972813

jeromerobert will probably speak for himself soon, but I think what he means and what I also think of this topic is that pdfarranger should continue to build and work without the additional dependencies needed for image support. (`setup.py` builds pdfarranger. Most people don't run it directly but through `pip install`.)

A few more of my thoughts to this topic:
- openjpeg is already a transitive dependency through poppler. Not sure if we can use it from python and/or if it helps with this task in any way though. 
- In general, if we can make it work without or with commonly available dependencies that would be appreciated. img2pdf seems to have a good coverage in the distributions with official pdfarranger packages ([repology](https://repology.org/badge/versions-matrix.svg?projects=pdfarranger,python:pikepdf%3E=1.7,img2pdf,python:img2pdf&header=pdfarranger%20packaging%20status) - note that python:img2pdf and img2pdf are the same).
- Bigger libraries often have a configure step where you tell the build system which build options you want to enable/disable. I am not sure if we can easily implement this with our current system or if it is needed at all. Alternatively pdfarranger can just check the availability of the needed dependencies at runtime and enable/disable functionality based on that.
- Keep user experience in mind, feel free to discuss it here before implementation. For example: What should happen when image dependencies are not available? Are there grayed out menu entries or are they not visible at all? Should the user be informed of this task? If yes, how? Pro: They know why the feature is missing. Con: Distracting. Non actionable for many users. Might make them unhappy. (I don't have an opinion on these questions yet, might also depend on other details of the implementation.)


Ping me for German translations when needed.

**Comment by dreua** [comment]
*Note to self: Have a thorough look at the code before writing too much :see_no_evil: *

It looks like you already have working code and have thought about most of the stuff I mentioned above. I was mislead by the Draft status and all the unchecked boxes, sorry about my redundant comments. I need to sleep now, will try to test your code and be more concentrated tomorrow.

**Comment by jeromerobert** [comment]
* By optional I mean that it must work without img2pdf which is what you almost did. We are just missing a `img2pdf=None` in the except to avoid `img2pdf not defined`.
* It should also be optional in `setup.py`. See https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to support `pip install pdfarranger[img2pdf]`.
* `PDFDoc` is already creating a temporary file. I think we don't need to have 2 temporary files (especially when the first one is not deleted). May be you could add an other PDFDoc constructor that get a buffer as input ?

Just some remark
* I removed `mimetypes` usage because of #101 but I don't mind readding it for images
* Having img2pdf in the Windows installer will require some work and I don't plan to do it. img2pdf will be for Linux user's only until someone do it.
* I think people will want a way to specify the DPI of the image (but let's keep that for an other issue/PR)

**Comment by mimi89999** [comment]
>     * By optional I mean that it must work without img2pdf which is what you almost did. We are just missing a `img2pdf=None` in the except to avoid `img2pdf not defined`.
Sorry, I missed that. Thanks for pointing that out.
>     * It should also be optional in `setup.py`. See https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to support `pip install pdfarranger[img2pdf]`.
Done
>     * `PDFDoc` is already creating a temporary file. I think we don't need to have 2 temporary files (especially when the first one is not deleted). May be you could add an other PDFDoc constructor that get a buffer as input ?
On my TODO

I also made the MIME handling way more robust, but the code isn't as nice now.

**Comment by mimi89999** [comment]
It should be ready now. @jeromerobert could you please review?

**Comment by jeromerobert** [comment]
* `setup.py` is missing the img2pdf dependency
* Please don't use MIME for pdf type (see  #101). Your previous version was better (check mime for image, else just try to open the PDF).

**Comment by jeromerobert** [comment]
You checked *Add translations (can do fr and pl)* but did not added those translation. If this is because you are concerned by the POT file synchronisation, don't bother. You can just regenerate the .pot file for you and commit only the line of the `fr.po` and `pl.po` files you modified.

**Comment by mimi89999** [comment]
>     * `setup.py` is missing the img2pdf dependency
Added
>     * Please don't use MIME for pdf type (see  #101). Your previous version was better (check mime for image, else just try to open the PDF).
I think that it's an issue with WPS Office and that MIME map shouldn't be changed.

> You checked Add translations (can do fr and pl) but did not added those translation.

Removed that task.

**Comment by jeromerobert** [comment]
Ok I agree that we should keep using `mimetypes`.

Now I get `NameError: name 'img2pdf_supported_img' is not defined` when trying your branch. You are missing a `img2pdf_supported_img=[]` right ?

**Comment by mimi89999** [comment]
L762-768 should be wrapped in `if img2pdf:`. Missed that. Sorry

**Comment by mimi89999** [comment]
I will push the change this evening. Is it OK besides that?

**Comment by jeromerobert** [comment]
> Is it OK besides that?

I think so.

**Comment by mimi89999** [comment]
Done

**Pull request merged**
